//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace APIManage.WebReferenceCC {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IHsCRMWebSrvbinding", Namespace="http://tempuri.org/")]
    public partial class IHsCRMWebSrvservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IWsPosCommOperateOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IHsCRMWebSrvservice() {
            this.Url = global::APIManage.Properties.Settings.Default.APIManage_WebReferenceCC_IHsCRMWebSrvservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IWsPosCommOperateCompletedEventHandler IWsPosCommOperateCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:HsCRMWebSrvIntf-IHsCRMWebSrv#IWsPosCommOperate", RequestNamespace="urn:HsCRMWebSrvIntf-IHsCRMWebSrv", ResponseNamespace="urn:HsCRMWebSrvIntf-IHsCRMWebSrv")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TReturnInfo IWsPosCommOperate(int piFunctionCode, string psInputPara) {
            object[] results = this.Invoke("IWsPosCommOperate", new object[] {
                        piFunctionCode,
                        psInputPara});
            return ((TReturnInfo)(results[0]));
        }
        
        /// <remarks/>
        public void IWsPosCommOperateAsync(int piFunctionCode, string psInputPara) {
            this.IWsPosCommOperateAsync(piFunctionCode, psInputPara, null);
        }
        
        /// <remarks/>
        public void IWsPosCommOperateAsync(int piFunctionCode, string psInputPara, object userState) {
            if ((this.IWsPosCommOperateOperationCompleted == null)) {
                this.IWsPosCommOperateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIWsPosCommOperateOperationCompleted);
            }
            this.InvokeAsync("IWsPosCommOperate", new object[] {
                        piFunctionCode,
                        psInputPara}, this.IWsPosCommOperateOperationCompleted, userState);
        }
        
        private void OnIWsPosCommOperateOperationCompleted(object arg) {
            if ((this.IWsPosCommOperateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IWsPosCommOperateCompleted(this, new IWsPosCommOperateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:HsCRMWebSrvIntf")]
    public partial class TReturnInfo {
        
        private string rtnMsgField;
        
        private string outputParaField;
        
        private int returnCodeField;
        
        /// <remarks/>
        public string RtnMsg {
            get {
                return this.rtnMsgField;
            }
            set {
                this.rtnMsgField = value;
            }
        }
        
        /// <remarks/>
        public string OutputPara {
            get {
                return this.outputParaField;
            }
            set {
                this.outputParaField = value;
            }
        }
        
        /// <remarks/>
        public int ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void IWsPosCommOperateCompletedEventHandler(object sender, IWsPosCommOperateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IWsPosCommOperateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IWsPosCommOperateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TReturnInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TReturnInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591