//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace APIManage.wemediacn {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SMSServiceSoap", Namespace="http://mms.wemediacn.com/")]
    public partial class SMSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBatchSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSMSCoveyOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySMSStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySmsSendRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback CanelSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySMSUPOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuerySmsSeqReportOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestTemplateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendTemplateSMSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SMSService() {
            this.Url = global::APIManage.Properties.Settings.Default.APIManage_wemediacn_SMSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendSMSCompletedEventHandler SendSMSCompleted;
        
        /// <remarks/>
        public event SendBatchSMSCompletedEventHandler SendBatchSMSCompleted;
        
        /// <remarks/>
        public event SendSMSCoveyCompletedEventHandler SendSMSCoveyCompleted;
        
        /// <remarks/>
        public event QuerySMSStateCompletedEventHandler QuerySMSStateCompleted;
        
        /// <remarks/>
        public event QuerySmsSendRecordCompletedEventHandler QuerySmsSendRecordCompleted;
        
        /// <remarks/>
        public event CanelSMSCompletedEventHandler CanelSMSCompleted;
        
        /// <remarks/>
        public event QuerySMSUPCompletedEventHandler QuerySMSUPCompleted;
        
        /// <remarks/>
        public event QuerySmsSeqReportCompletedEventHandler QuerySmsSeqReportCompleted;
        
        /// <remarks/>
        public event TestTemplateCompletedEventHandler TestTemplateCompleted;
        
        /// <remarks/>
        public event SendTemplateSMSCompletedEventHandler SendTemplateSMSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/SendSMS", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMS(string mobile, int FormatID, string Content, System.DateTime ScheduleDate, string TokenID) {
            object[] results = this.Invoke("SendSMS", new object[] {
                        mobile,
                        FormatID,
                        Content,
                        ScheduleDate,
                        TokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSAsync(string mobile, int FormatID, string Content, System.DateTime ScheduleDate, string TokenID) {
            this.SendSMSAsync(mobile, FormatID, Content, ScheduleDate, TokenID, null);
        }
        
        /// <remarks/>
        public void SendSMSAsync(string mobile, int FormatID, string Content, System.DateTime ScheduleDate, string TokenID, object userState) {
            if ((this.SendSMSOperationCompleted == null)) {
                this.SendSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSOperationCompleted);
            }
            this.InvokeAsync("SendSMS", new object[] {
                        mobile,
                        FormatID,
                        Content,
                        ScheduleDate,
                        TokenID}, this.SendSMSOperationCompleted, userState);
        }
        
        private void OnSendSMSOperationCompleted(object arg) {
            if ((this.SendSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCompleted(this, new SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/SendBatchSMS", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendBatchSMS(string mobileList, int FormatID, string Content, System.DateTime deadLineTime, string TokenID) {
            object[] results = this.Invoke("SendBatchSMS", new object[] {
                        mobileList,
                        FormatID,
                        Content,
                        deadLineTime,
                        TokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendBatchSMSAsync(string mobileList, int FormatID, string Content, System.DateTime deadLineTime, string TokenID) {
            this.SendBatchSMSAsync(mobileList, FormatID, Content, deadLineTime, TokenID, null);
        }
        
        /// <remarks/>
        public void SendBatchSMSAsync(string mobileList, int FormatID, string Content, System.DateTime deadLineTime, string TokenID, object userState) {
            if ((this.SendBatchSMSOperationCompleted == null)) {
                this.SendBatchSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBatchSMSOperationCompleted);
            }
            this.InvokeAsync("SendBatchSMS", new object[] {
                        mobileList,
                        FormatID,
                        Content,
                        deadLineTime,
                        TokenID}, this.SendBatchSMSOperationCompleted, userState);
        }
        
        private void OnSendBatchSMSOperationCompleted(object arg) {
            if ((this.SendBatchSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBatchSMSCompleted(this, new SendBatchSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/SendSMSCovey", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendSMSCovey(string XMLStr, string TokenID) {
            object[] results = this.Invoke("SendSMSCovey", new object[] {
                        XMLStr,
                        TokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendSMSCoveyAsync(string XMLStr, string TokenID) {
            this.SendSMSCoveyAsync(XMLStr, TokenID, null);
        }
        
        /// <remarks/>
        public void SendSMSCoveyAsync(string XMLStr, string TokenID, object userState) {
            if ((this.SendSMSCoveyOperationCompleted == null)) {
                this.SendSMSCoveyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSMSCoveyOperationCompleted);
            }
            this.InvokeAsync("SendSMSCovey", new object[] {
                        XMLStr,
                        TokenID}, this.SendSMSCoveyOperationCompleted, userState);
        }
        
        private void OnSendSMSCoveyOperationCompleted(object arg) {
            if ((this.SendSMSCoveyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSMSCoveyCompleted(this, new SendSMSCoveyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/QuerySMSState", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySMSState(string MessageID) {
            object[] results = this.Invoke("QuerySMSState", new object[] {
                        MessageID});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySMSStateAsync(string MessageID) {
            this.QuerySMSStateAsync(MessageID, null);
        }
        
        /// <remarks/>
        public void QuerySMSStateAsync(string MessageID, object userState) {
            if ((this.QuerySMSStateOperationCompleted == null)) {
                this.QuerySMSStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySMSStateOperationCompleted);
            }
            this.InvokeAsync("QuerySMSState", new object[] {
                        MessageID}, this.QuerySMSStateOperationCompleted, userState);
        }
        
        private void OnQuerySMSStateOperationCompleted(object arg) {
            if ((this.QuerySMSStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySMSStateCompleted(this, new QuerySMSStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/QuerySmsSendRecord", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySmsSendRecord(System.DateTime time, int MinID, string TokenID) {
            object[] results = this.Invoke("QuerySmsSendRecord", new object[] {
                        time,
                        MinID,
                        TokenID});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySmsSendRecordAsync(System.DateTime time, int MinID, string TokenID) {
            this.QuerySmsSendRecordAsync(time, MinID, TokenID, null);
        }
        
        /// <remarks/>
        public void QuerySmsSendRecordAsync(System.DateTime time, int MinID, string TokenID, object userState) {
            if ((this.QuerySmsSendRecordOperationCompleted == null)) {
                this.QuerySmsSendRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySmsSendRecordOperationCompleted);
            }
            this.InvokeAsync("QuerySmsSendRecord", new object[] {
                        time,
                        MinID,
                        TokenID}, this.QuerySmsSendRecordOperationCompleted, userState);
        }
        
        private void OnQuerySmsSendRecordOperationCompleted(object arg) {
            if ((this.QuerySmsSendRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySmsSendRecordCompleted(this, new QuerySmsSendRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/CanelSMS", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CanelSMS(string MessageID) {
            object[] results = this.Invoke("CanelSMS", new object[] {
                        MessageID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CanelSMSAsync(string MessageID) {
            this.CanelSMSAsync(MessageID, null);
        }
        
        /// <remarks/>
        public void CanelSMSAsync(string MessageID, object userState) {
            if ((this.CanelSMSOperationCompleted == null)) {
                this.CanelSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCanelSMSOperationCompleted);
            }
            this.InvokeAsync("CanelSMS", new object[] {
                        MessageID}, this.CanelSMSOperationCompleted, userState);
        }
        
        private void OnCanelSMSOperationCompleted(object arg) {
            if ((this.CanelSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CanelSMSCompleted(this, new CanelSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/QuerySMSUP", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySMSUP(int MinID, int Count, string TokenID, string externCode) {
            object[] results = this.Invoke("QuerySMSUP", new object[] {
                        MinID,
                        Count,
                        TokenID,
                        externCode});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySMSUPAsync(int MinID, int Count, string TokenID, string externCode) {
            this.QuerySMSUPAsync(MinID, Count, TokenID, externCode, null);
        }
        
        /// <remarks/>
        public void QuerySMSUPAsync(int MinID, int Count, string TokenID, string externCode, object userState) {
            if ((this.QuerySMSUPOperationCompleted == null)) {
                this.QuerySMSUPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySMSUPOperationCompleted);
            }
            this.InvokeAsync("QuerySMSUP", new object[] {
                        MinID,
                        Count,
                        TokenID,
                        externCode}, this.QuerySMSUPOperationCompleted, userState);
        }
        
        private void OnQuerySMSUPOperationCompleted(object arg) {
            if ((this.QuerySMSUPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySMSUPCompleted(this, new QuerySMSUPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/QuerySmsSeqReport", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlElement QuerySmsSeqReport(int MinID, string TokenID) {
            object[] results = this.Invoke("QuerySmsSeqReport", new object[] {
                        MinID,
                        TokenID});
            return ((System.Xml.XmlElement)(results[0]));
        }
        
        /// <remarks/>
        public void QuerySmsSeqReportAsync(int MinID, string TokenID) {
            this.QuerySmsSeqReportAsync(MinID, TokenID, null);
        }
        
        /// <remarks/>
        public void QuerySmsSeqReportAsync(int MinID, string TokenID, object userState) {
            if ((this.QuerySmsSeqReportOperationCompleted == null)) {
                this.QuerySmsSeqReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySmsSeqReportOperationCompleted);
            }
            this.InvokeAsync("QuerySmsSeqReport", new object[] {
                        MinID,
                        TokenID}, this.QuerySmsSeqReportOperationCompleted, userState);
        }
        
        private void OnQuerySmsSeqReportOperationCompleted(object arg) {
            if ((this.QuerySmsSeqReportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySmsSeqReportCompleted(this, new QuerySmsSeqReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/TestTemplate", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestTemplate(int templateId, string paramType, string paramData, string TokenID) {
            object[] results = this.Invoke("TestTemplate", new object[] {
                        templateId,
                        paramType,
                        paramData,
                        TokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestTemplateAsync(int templateId, string paramType, string paramData, string TokenID) {
            this.TestTemplateAsync(templateId, paramType, paramData, TokenID, null);
        }
        
        /// <remarks/>
        public void TestTemplateAsync(int templateId, string paramType, string paramData, string TokenID, object userState) {
            if ((this.TestTemplateOperationCompleted == null)) {
                this.TestTemplateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestTemplateOperationCompleted);
            }
            this.InvokeAsync("TestTemplate", new object[] {
                        templateId,
                        paramType,
                        paramData,
                        TokenID}, this.TestTemplateOperationCompleted, userState);
        }
        
        private void OnTestTemplateOperationCompleted(object arg) {
            if ((this.TestTemplateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestTemplateCompleted(this, new TestTemplateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://mms.wemediacn.com/SendTemplateSMS", RequestNamespace="http://mms.wemediacn.com/", ResponseNamespace="http://mms.wemediacn.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendTemplateSMS(string mobile, int FormatID, int templateId, string paramType, string paramData, string TokenID) {
            object[] results = this.Invoke("SendTemplateSMS", new object[] {
                        mobile,
                        FormatID,
                        templateId,
                        paramType,
                        paramData,
                        TokenID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendTemplateSMSAsync(string mobile, int FormatID, int templateId, string paramType, string paramData, string TokenID) {
            this.SendTemplateSMSAsync(mobile, FormatID, templateId, paramType, paramData, TokenID, null);
        }
        
        /// <remarks/>
        public void SendTemplateSMSAsync(string mobile, int FormatID, int templateId, string paramType, string paramData, string TokenID, object userState) {
            if ((this.SendTemplateSMSOperationCompleted == null)) {
                this.SendTemplateSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTemplateSMSOperationCompleted);
            }
            this.InvokeAsync("SendTemplateSMS", new object[] {
                        mobile,
                        FormatID,
                        templateId,
                        paramType,
                        paramData,
                        TokenID}, this.SendTemplateSMSOperationCompleted, userState);
        }
        
        private void OnSendTemplateSMSOperationCompleted(object arg) {
            if ((this.SendTemplateSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTemplateSMSCompleted(this, new SendTemplateSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendSMSCompletedEventHandler(object sender, SendSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendBatchSMSCompletedEventHandler(object sender, SendBatchSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBatchSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBatchSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendSMSCoveyCompletedEventHandler(object sender, SendSMSCoveyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSMSCoveyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSMSCoveyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QuerySMSStateCompletedEventHandler(object sender, QuerySMSStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySMSStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySMSStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QuerySmsSendRecordCompletedEventHandler(object sender, QuerySmsSendRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySmsSendRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySmsSendRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void CanelSMSCompletedEventHandler(object sender, CanelSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CanelSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CanelSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QuerySMSUPCompletedEventHandler(object sender, QuerySMSUPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySMSUPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySMSUPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QuerySmsSeqReportCompletedEventHandler(object sender, QuerySmsSeqReportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySmsSeqReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuerySmsSeqReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlElement Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlElement)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TestTemplateCompletedEventHandler(object sender, TestTemplateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestTemplateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestTemplateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SendTemplateSMSCompletedEventHandler(object sender, SendTemplateSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTemplateSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTemplateSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591